name: Build & Release Electron App

on:
  push:
    branches:
      - main

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build & Package (macOS)
        run: npm run build:mac
      - name: Upload mac artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: |
            dist/*.dmg
            dist/*.zip
            dist/*.pkg
            dist/*.json
            dist/*.yml

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build & Package (Windows)
        run: npm run build:win
      - name: Upload win artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            dist/*.exe
            dist/*.msi
            dist/*.json
            dist/*.yml

  release:
    needs: [build-mac, build-win]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download mac artifact
        uses: actions/download-artifact@v4
        with:
          name: mac-build
          path: release-artifacts/mac
      - name: Download win artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: release-artifacts/win
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.ref_name }}
          name: Release v${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Assets (mac)
        uses: softprops/action-gh-release@v2
        with:
          files: release-artifacts/mac/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Assets (win)
        uses: softprops/action-gh-release@v2
        with:
          files: release-artifacts/win/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
