name: Build & Release Electron App
on:
  push:
    tags:
      - 'v*'

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build & Package (macOS)
        run: npm run build:mac
      - name: Upload mac artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: |
            dist/*.dmg
            dist/*.zip
            dist/*.pkg
            dist/latest-mac.yml  # 明确指定 yml 文件

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build & Package (Windows)
        run: npm run build:win
      - name: Upload win artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            dist/*.exe
            dist/*.msi
            dist/latest.yml      # 明确指定 yml 文件

  release:
    needs: [build-mac, build-win]
    runs-on: ubuntu-latest
    steps:
      - name: Download mac artifact
        uses: actions/download-artifact@v4
        with:
          name: mac-build
          path: release-artifacts/mac
      - name: Download win artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: release-artifacts/win

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          # 修正 1: 直接使用 github.ref_name，它就是觸發的標籤 (e.g., "v1.0.0")
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          # 修正 2: 將所有檔案的路徑一次性提供給 files 參數
          files: |
            release-artifacts/mac/*
            release-artifacts/win/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
