name: Build & Release Electron App
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # 1. 新增手動觸發功能
jobs:
  release: # 1. 將所有步驟合併到一個 release 工作中
    runs-on: ${{ matrix.os }} # 2. 使用 matrix 策略來跨平台

    strategy:
      matrix:
        os: [macos-latest, windows-latest] # 為 macOS 和 Windows 建立矩陣

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build and release on Windows
        if: runner.os == 'Windows' # <--- 只有在 Windows 上才執行此步驟
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and release on macOS
        if: runner.os == 'macOS' # <--- 只有在 macOS 上才執行此步驟
        run: npm run build:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
